import React, { useState } from 'react';
import { Message, Sender } from '../types';

interface ChatMessageProps {
  message: Message;
}

const ChatMessage: React.FC<ChatMessageProps> = ({ message }) => {
  const isUser = message.sender === Sender.USER;
  const isSonic = message.sender === Sender.SONIC;
  const [isSpeaking, setIsSpeaking] = useState(false);

  const handleSpeak = () => {
    if ('speechSynthesis' in window) {
      if (isSpeaking) {
        window.speechSynthesis.cancel();
        setIsSpeaking(false);
        return;
      }

      const utterance = new SpeechSynthesisUtterance(message.text);
      // Try to find a good voice
      const voices = window.speechSynthesis.getVoices();
      const hindiVoice = voices.find(v => v.lang.includes('hi'));
      const englishVoice = voices.find(v => v.lang.includes('en-US') || v.lang.includes('en-GB'));
      
      if (hindiVoice && /[\u0900-\u097F]/.test(message.text)) {
          utterance.voice = hindiVoice;
      } else if (englishVoice) {
          utterance.voice = englishVoice;
      }
      
      utterance.rate = 1.1; // Slightly faster like Sonic
      utterance.pitch = 1.0;

      utterance.onend = () => setIsSpeaking(false);
      utterance.onerror = () => setIsSpeaking(false);

      setIsSpeaking(true);
      window.speechSynthesis.speak(utterance);
    }
  };
  
  return (
    <div className={`flex w-full mb-6 ${isUser ? 'justify-end' : 'justify-start'}`}>
      <div className={`flex max-w-[85%] md:max-w-[75%] ${isUser ? 'flex-row-reverse' : 'flex-row'} items-end gap-3`}>
        
        {/* Avatar */}
        <div className={`w-9 h-9 rounded-full flex items-center justify-center shrink-0 border-2 shadow-lg ${
          isUser ? 'bg-gray-800 border-gray-600 text-gray-400' : 'bg-blue-600 border-yellow-400 text-white shadow-blue-500/50'
        }`}>
          <i className={`fas ${isUser ? 'fa-user' : 'fa-bolt'}`}></i>
        </div>

        {/* Bubble */}
        <div className={`relative px-5 py-3 rounded-2xl text-sm md:text-base leading-relaxed shadow-lg ${
          isUser 
            ? 'bg-gray-800 text-gray-100 rounded-br-none border border-gray-700' 
            : 'bg-gradient-to-br from-blue-600 to-blue-700 text-white rounded-bl-none border border-blue-500'
        }`}>
          {/* User Attachment (Image) */}
          {message.attachment && (
            <div className="mb-3 rounded-lg overflow-hidden border border-gray-600 shadow-md">
              <img 
                src={`data:${message.attachment.mimeType};base64,${message.attachment.data}`}
                alt="Uploaded by user"
                className="w-full h-auto max-w-[200px] object-cover"
              />
            </div>
          )}

          {/* Generated Image or Text */}
          {message.imageSrc ? (
             <div className="flex flex-col gap-2">
                 {message.text && <p className="mb-2 selectable-text">{message.text}</p>}
                 <div className="relative rounded-lg overflow-hidden border-2 border-yellow-400 shadow-xl group">
                     <img 
                        src={message.imageSrc} 
                        alt="Generated by Sonic" 
                        className="w-full h-auto max-w-sm object-cover"
                        loading="lazy" 
                     />
                 </div>
             </div>
          ) : (
            <div className="whitespace-pre-wrap selectable-text">{message.text}</div>
          )}
          
          {/* Thinking Indicator */}
          {message.isThinking && (
             <div className="flex gap-1 mt-2 justify-center h-4 items-center">
                 <div className="w-2 h-2 bg-yellow-400 rounded-full animate-bounce" style={{ animationDelay: '0s' }}></div>
                 <div className="w-2 h-2 bg-yellow-400 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
                 <div className="w-2 h-2 bg-yellow-400 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
             </div>
          )}

          {/* Text to Speech Button for Sonic */}
          {isSonic && !message.isThinking && !message.imageSrc && message.text && (
            <div className="absolute -bottom-6 left-0 flex items-center gap-2">
                <button 
                  onClick={handleSpeak}
                  className={`text-xs flex items-center gap-1 font-semibold transition-colors ${isSpeaking ? 'text-yellow-400 animate-pulse' : 'text-gray-400 hover:text-white'}`}
                  title="Read Aloud"
                >
                  <i className={`fas ${isSpeaking ? 'fa-volume-up' : 'fa-volume-low'}`}></i>
                  {isSpeaking ? 'Stop' : 'Read'}
                </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ChatMessage;